// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosizeTextareaController from "./autosize_textarea_controller"
application.register("autosize-textarea", AutosizeTextareaController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
