// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveLinkController from "./active_link_controller"
application.register("active-link", ActiveLinkController)

import AutosizeTextareaController from "./autosize_textarea_controller"
application.register("autosize-textarea", AutosizeTextareaController)

import DisableFieldsController from "./disable_fields_controller"
application.register("disable-fields", DisableFieldsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
